# -*- coding: utf-8 -*-
"""Technical Portfolio (Python/ESG Analytics) .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XgMQ_AfP4-9RzebtUzGTRUvTOB1Zu72q
"""

"""
Project: AI-Driven Business Analytics for ESG Performance
Author: Athina Stavropoulou
Description: This script performs an end-to-end data analysis on how AI maturity and
             predictive analytics correlate with ESG scores across 27 global corporations.
             Techniques used: Data Cleaning, EDA, Correlation Analysis, and K-Means Clustering.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# ==========================================
# 1. CONFIGURATION & STYLING
# ==========================================
# Setting a professional theme for visualizations
sns.set_theme(style="whitegrid")
plt.rcParams['figure.figsize'] = [12, 7]
plt.rcParams['figure.dpi'] = 100

# ==========================================
# 2. DATA LOADING & PREPROCESSING
# ==========================================
print("--- [Step 1] Data Loading & Preprocessing ---")

# Load the dataset (using ';' as separator based on initial structure)
file_path = 'AI_ESG_Analytics_Template.csv'
try:
    df = pd.read_csv(file_path, sep=';')
except FileNotFoundError:
    print(f"Error: {file_path} not found. Please ensure the file is in the working directory.")

# Data Cleaning: Remove artifacts from CSV export (Unnamed columns)
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

# Convert key metrics to numeric, handling potential formatting issues (e.g., European comma usage)
numeric_metrics = [
    'AI_Maturity_Score', 'ESG_Score', 'Environmental_Score',
    'Social_Score', 'Governance_Score', 'Use_of_Predictive_Analytics',
    'Data_Driven_Decision_Making', 'Tech_Investment_(Million_$)',
    'Revenue_(Million_$)'
]

for col in numeric_metrics:
    # Coerce errors to NaN and drop them to ensure analytical consistency
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.dropna(subset=numeric_metrics, inplace=True)

# ==========================================
# 3. DATA CORRECTION (Outlier Handling)
# ==========================================
print("--- [Step 2] Outlier Correction ---")

# Fix ESG Score scaling (e.g., 33.3 -> 3.33)
# Assumption: High values (>10) are decimal errors
esg_outliers = df['ESG_Score'] > 10
if esg_outliers.any():
    print(f"Correcting {esg_outliers.sum()} entries in ESG Score.")
    df.loc[esg_outliers, 'ESG_Score'] = df.loc[esg_outliers, 'ESG_Score'] / 10

# Handling extreme Tech Investment outliers (e.g., >$500B)
# Replacing outliers with the median to prevent skewed visualizations
tech_limit = 500000
tech_outliers = df['Tech_Investment_(Million_$)'] > tech_limit
if tech_outliers.any():
    median_tech = df['Tech_Investment_(Million_$)'].median()
    print(f"Detected {tech_outliers.sum()} outliers in Tech Investment. Imputing with median: {median_tech}")
    df.loc[tech_outliers, 'Tech_Investment_(Million_$)'] = median_tech

# ==========================================
# 4. EXPLORATORY DATA ANALYSIS (EDA)
# ==========================================
print("\n--- [Step 3] Descriptive Statistics ---")
print(df[numeric_metrics].describe().T)

# Visualization 1: Digital Capabilities Distribution
plt.figure()
sns.boxplot(data=df[['AI_Maturity_Score', 'Use_of_Predictive_Analytics', 'Data_Driven_Decision_Making']])
plt.title('Distribution of AI Maturity & Analytics Capabilities', fontsize=15)
plt.ylabel('Scale (0-5)')
plt.show()

# Visualization 2: ESG Score Distribution (Bimodal Check)
plt.figure()
sns.histplot(df['ESG_Score'], bins=10, kde=True, color='#2ecc71')
plt.title('Histogram of ESG Scores: Identifying Performance Clusters', fontsize=15)
plt.xlabel('Combined ESG Score')
plt.show()

# ==========================================
# 5. INDUSTRIAL COMPARATIVE ANALYSIS
# ==========================================
print("\n--- [Step 4] Industry Benchmarking ---")

# Grouping by Industry for mean AI Maturity
industry_ai = df.groupby('Industry')['AI_Maturity_Score'].mean().sort_values()
plt.figure()
sns.barplot(x=industry_ai.values, y=industry_ai.index, palette='viridis')
plt.title('Average AI Maturity Level per Industry Segment', fontsize=15)
plt.xlabel('AI Maturity Index')
plt.show()

# Side-by-Side Industry Comparison: ESG vs AI
industry_comparison = df.groupby('Industry')[['ESG_Score', 'AI_Maturity_Score']].mean()
industry_comparison.plot(kind='bar', figsize=(14, 6), color=['#3498db', '#e67e22'])
plt.title('Strategic Comparison: ESG Performance vs Digital Maturity by Sector', fontsize=15)
plt.ylabel('Mean Score')
plt.xticks(rotation=45, ha='right')
plt.legend(frameon=True)
plt.show()

# ==========================================
# 6. CORRELATION ANALYSIS
# ==========================================
print("\n--- [Step 5] Statistical Correlations (Pearson) ---")

# Generating Heatmap for the Research Matrix
research_cols = ['ESG_Score', 'AI_Maturity_Score', 'Environmental_Score', 'Governance_Score', 'Data_Driven_Decision_Making']
plt.figure(figsize=(10, 8))
sns.heatmap(df[research_cols].corr(), annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Research Correlation Matrix: AI Maturity & ESG Pillars', fontsize=15)
plt.show()

# ==========================================
# 7. ADVANCED ANALYTICS: K-MEANS CLUSTERING
# ==========================================
print("\n--- [Step 6] Customer-Centric Segmentation (K-Means) ---")

# Features selected for strategic segmentation
cluster_features = ['ESG_Score', 'AI_Maturity_Score', 'Tech_Investment_(Million_$)']
X = df[cluster_features].copy()

# Standardizing features is crucial as Tech Investment has a different scale than Scores
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Applying K-Means with 3 predefined strategic segments
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
df['Cluster'] = kmeans.fit_predict(X_scaled)

# Dynamic Cluster Labeling based on Group Means
cluster_means = df.groupby('Cluster')[['ESG_Score', 'AI_Maturity_Score']].mean()

def map_labels(cluster_id):
    if cluster_id == cluster_means['ESG_Score'].idxmax():
        return 'ESG-AI Leader'
    elif cluster_id == cluster_means['ESG_Score'].idxmin():
        return 'Sustainability Laggard'
    else:
        return 'Tech Disruptor / Mid-Performer'

df['Strategic_Segment'] = df['Cluster'].apply(map_labels)

# Final Visualization: Strategic Segments Mapping
plt.figure()
sns.scatterplot(
    data=df, x='AI_Maturity_Score', y='ESG_Score',
    hue='Strategic_Segment', style='Strategic_Segment',
    s=200, palette='Set1', alpha=0.8
)
plt.title('Market Segmentation: AI Maturity vs. Sustainability Performance', fontsize=15)
plt.legend(title='Strategic Segment', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

print("\nFinal Company Classification (Sample):")
print(df[['Company', 'Industry', 'Strategic_Segment']].head(10))